# Generated by Django 5.1.1 on 2024-09-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('pub', 'Published'), ('drf', 'Draft')], default='drf', max_length=3),
        ),
    ]
